[project]
name = "goit-ds-hw-01"
version = "0.1.0"
description = ""
authors = [
    {name = "Viktoria0107",email = "viktorija.panchenko@gmail.com"}
]


readme = "README.md"
requires-python = "3.13"



[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
